# Generated by Django 4.0.3 on 2022-06-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GP_Glubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Description', models.TextField()),
                ('Price', models.FloatField(default=0)),
                ('Product_Image', models.ImageField(default=None, max_length=250, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Jersey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Description', models.TextField()),
                ('Price', models.FloatField(default=0)),
                ('Product_Image', models.ImageField(default=None, max_length=250, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Description', models.TextField()),
                ('Price', models.FloatField(default=0)),
                ('Product_Image', models.ImageField(default=None, max_length=250, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Description', models.TextField()),
                ('Price', models.FloatField(default=0)),
                ('Product_Image', models.ImageField(default=None, max_length=250, upload_to='products/')),
            ],
        ),
    ]
