# Generated by Django 4.0.3 on 2022-06-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_gp_glubs_jersey_others_shoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='Product_Name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
