# Generated by Django 4.0.3 on 2022-06-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_others_product_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GP_Glubs',
            new_name='GP_Glub',
        ),
        migrations.RenameModel(
            old_name='Others',
            new_name='Other',
        ),
        migrations.RenameModel(
            old_name='Shoes',
            new_name='Shoe',
        ),
    ]
